# Multiple Linear Regression

## Importing the libraries

In [49]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [50]:
dataset = pd.read_csv('weatherHistory.csv')
X = dataset[["Apparent Temperature (C)","Humidity","Pressure (millibars)","Visibility (km)"]].values
y = dataset.loc[:, "Temperature (C)"].values

In [51]:
print(X)

[[7.39e+00 8.90e-01 1.02e+03 1.58e+01]
 [7.23e+00 8.60e-01 1.02e+03 1.58e+01]
 [9.38e+00 8.90e-01 1.02e+03 1.50e+01]
 ...
 [6.81e+00 9.30e-01 1.02e+03 8.13e+00]
 [5.68e+00 9.30e-01 1.02e+03 6.30e+00]
 [6.08e+00 9.20e-01 1.02e+03 6.84e+00]]


## Encoding categorical data

In [52]:
"""from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))"""

"from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\nct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')\nX = np.array(ct.fit_transform(X))"

In [53]:
print(X)

[[7.39e+00 8.90e-01 1.02e+03 1.58e+01]
 [7.23e+00 8.60e-01 1.02e+03 1.58e+01]
 [9.38e+00 8.90e-01 1.02e+03 1.50e+01]
 ...
 [6.81e+00 9.30e-01 1.02e+03 8.13e+00]
 [5.68e+00 9.30e-01 1.02e+03 6.30e+00]
 [6.08e+00 9.20e-01 1.02e+03 6.84e+00]]


## Splitting the dataset into the Training set and Test set

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [57]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
from sklearn.metrics import mean_squared_error, r2_score
print("Linear Regression coeficients")
print("Slope = ",regressor.coef_[0])
print("Intercept = ",regressor.intercept_)
print("MSE = ",mean_squared_error(y_test,y_pred))
print("R2 = ",r2_score(y_test, y_pred))


Linear Regression coeficients
Slope =  0.8670206644423376
Intercept =  4.3358405411435985
MSE =  1.3040429428714841
R2 =  0.989150767924003


## Predicting the Test set results

In [56]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[20.22 20.56]
 [ 3.39  3.74]
 [16.07 15.03]
 ...
 [21.07 21.19]
 [ 9.42  8.66]
 [21.91 22.04]]
